---
- name: Playbook to download and extract archive 
  hosts: webservers
  become: true
  tasks:

  - name: Install tuned package
    apt:
      update_cache: true
      name: tuned
      state: latest

  - name: Make sure tuned is started and enabled
    systemd:
      name: tuned
      state: started
      enabled: true
  
  - name: Control tuned service status
    shell:  service tuned status
