---
- name: Create motd with ansible gathered facts
  hosts: ubuntu
  become: true
  gather_facts: true
  vars:
    motd_text: |
      
      Hostname: {{ ansible_hostname }}
      IP address: {{ ansible_host }}
      Have a nice day, admin!   
  
  tasks:

    - name: Create script file
      copy:
        content: "{{motd_text}}"
        dest: /etc/motd